package com.marisareis.jogo;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {
    
    Jogo novoJogo = new Jogo(); 
    
    URL url = this.getClass().getResource("/com/marisareis/img/hangmanIcon.png");
    Image iconeJanela = Toolkit.getDefaultToolkit().getImage(url);
    
    // icon do lblForca
    ImageIcon iconForca;
    
    List<String> letrasDigitadas = new ArrayList<>();
    
    public Main() {
        initComponents();
        // cor do JFrame
        Color background = new Color(18, 18, 19, 255);
        this.getContentPane().setBackground(background);
        
        // icon do JFrame
       this.setIconImage(iconeJanela);
       
       // icon do lblForca
       atualizarForca();
       lblForca.setIcon(iconForca);
    
       lblPalavraChave.setText(novoJogo.atualizarJogo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblForca = new javax.swing.JLabel();
        lblPalavraChave = new javax.swing.JLabel();
        btnQ = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnCedilha = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        txtJogada = new javax.swing.JTextField();
        txtLetrasUsadas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jogo da Forca");
        setResizable(false);

        lblForca.setBackground(new java.awt.Color(255, 204, 204));
        lblForca.setForeground(new java.awt.Color(255, 204, 204));
        lblForca.setPreferredSize(new java.awt.Dimension(400, 400));

        lblPalavraChave.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        lblPalavraChave.setForeground(new java.awt.Color(255, 255, 255));
        lblPalavraChave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnQ.setBackground(new java.awt.Color(129, 131, 132));
        btnQ.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnQ.setForeground(new java.awt.Color(255, 255, 255));
        btnQ.setText("Q");
        btnQ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQ.setPreferredSize(new java.awt.Dimension(100, 50));
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });

        btnN.setBackground(new java.awt.Color(129, 131, 132));
        btnN.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnN.setForeground(new java.awt.Color(255, 255, 255));
        btnN.setText("N");
        btnN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnN.setPreferredSize(new java.awt.Dimension(100, 50));
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnW.setBackground(new java.awt.Color(129, 131, 132));
        btnW.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnW.setForeground(new java.awt.Color(255, 255, 255));
        btnW.setText("W");
        btnW.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnW.setPreferredSize(new java.awt.Dimension(100, 50));
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        btnM.setBackground(new java.awt.Color(129, 131, 132));
        btnM.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnM.setForeground(new java.awt.Color(255, 255, 255));
        btnM.setText("M");
        btnM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnM.setPreferredSize(new java.awt.Dimension(100, 50));
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(129, 131, 132));
        btnE.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnE.setForeground(new java.awt.Color(255, 255, 255));
        btnE.setText("E");
        btnE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnE.setPreferredSize(new java.awt.Dimension(100, 50));
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(129, 131, 132));
        btnDel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("←");
        btnDel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDel.setPreferredSize(new java.awt.Dimension(100, 50));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnR.setBackground(new java.awt.Color(129, 131, 132));
        btnR.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnR.setForeground(new java.awt.Color(255, 255, 255));
        btnR.setText("R");
        btnR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnR.setPreferredSize(new java.awt.Dimension(100, 50));
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btnZ.setBackground(new java.awt.Color(129, 131, 132));
        btnZ.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnZ.setForeground(new java.awt.Color(255, 255, 255));
        btnZ.setText("Z");
        btnZ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnZ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnZ.setPreferredSize(new java.awt.Dimension(100, 50));
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });

        btnT.setBackground(new java.awt.Color(129, 131, 132));
        btnT.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnT.setForeground(new java.awt.Color(255, 255, 255));
        btnT.setText("T");
        btnT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnT.setPreferredSize(new java.awt.Dimension(100, 50));
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        btnY.setBackground(new java.awt.Color(129, 131, 132));
        btnY.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnY.setForeground(new java.awt.Color(255, 255, 255));
        btnY.setText("Y");
        btnY.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnY.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnY.setPreferredSize(new java.awt.Dimension(100, 50));
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        btnX.setBackground(new java.awt.Color(129, 131, 132));
        btnX.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnX.setForeground(new java.awt.Color(255, 255, 255));
        btnX.setText("X");
        btnX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnX.setPreferredSize(new java.awt.Dimension(100, 50));
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(129, 131, 132));
        btnC.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setText("C");
        btnC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnC.setPreferredSize(new java.awt.Dimension(100, 50));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnU.setBackground(new java.awt.Color(129, 131, 132));
        btnU.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnU.setForeground(new java.awt.Color(255, 255, 255));
        btnU.setText("U");
        btnU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnU.setPreferredSize(new java.awt.Dimension(100, 50));
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnI.setBackground(new java.awt.Color(129, 131, 132));
        btnI.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnI.setForeground(new java.awt.Color(255, 255, 255));
        btnI.setText("I");
        btnI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnI.setPreferredSize(new java.awt.Dimension(100, 50));
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnO.setBackground(new java.awt.Color(129, 131, 132));
        btnO.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnO.setForeground(new java.awt.Color(255, 255, 255));
        btnO.setText("O");
        btnO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnO.setPreferredSize(new java.awt.Dimension(100, 50));
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        btnP.setBackground(new java.awt.Color(129, 131, 132));
        btnP.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnP.setForeground(new java.awt.Color(255, 255, 255));
        btnP.setText("P");
        btnP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnP.setPreferredSize(new java.awt.Dimension(100, 50));
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnF.setBackground(new java.awt.Color(129, 131, 132));
        btnF.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnF.setForeground(new java.awt.Color(255, 255, 255));
        btnF.setText("F");
        btnF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnF.setPreferredSize(new java.awt.Dimension(100, 50));
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnG.setBackground(new java.awt.Color(129, 131, 132));
        btnG.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnG.setForeground(new java.awt.Color(255, 255, 255));
        btnG.setText("G");
        btnG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnG.setPreferredSize(new java.awt.Dimension(100, 50));
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnH.setBackground(new java.awt.Color(129, 131, 132));
        btnH.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnH.setForeground(new java.awt.Color(255, 255, 255));
        btnH.setText("H");
        btnH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnH.setPreferredSize(new java.awt.Dimension(100, 50));
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });

        btnJ.setBackground(new java.awt.Color(129, 131, 132));
        btnJ.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnJ.setForeground(new java.awt.Color(255, 255, 255));
        btnJ.setText("J");
        btnJ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJ.setPreferredSize(new java.awt.Dimension(100, 50));
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });

        btnK.setBackground(new java.awt.Color(129, 131, 132));
        btnK.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnK.setForeground(new java.awt.Color(255, 255, 255));
        btnK.setText("K");
        btnK.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnK.setPreferredSize(new java.awt.Dimension(100, 50));
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });

        btnL.setBackground(new java.awt.Color(129, 131, 132));
        btnL.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnL.setForeground(new java.awt.Color(255, 255, 255));
        btnL.setText("L");
        btnL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnL.setPreferredSize(new java.awt.Dimension(100, 50));
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        btnCedilha.setBackground(new java.awt.Color(129, 131, 132));
        btnCedilha.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnCedilha.setForeground(new java.awt.Color(255, 255, 255));
        btnCedilha.setText("Ç");
        btnCedilha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCedilha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCedilha.setPreferredSize(new java.awt.Dimension(100, 50));
        btnCedilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCedilhaActionPerformed(evt);
            }
        });

        btnA.setBackground(new java.awt.Color(129, 131, 132));
        btnA.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnA.setForeground(new java.awt.Color(255, 255, 255));
        btnA.setText("A");
        btnA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnA.setPreferredSize(new java.awt.Dimension(100, 50));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnS.setBackground(new java.awt.Color(129, 131, 132));
        btnS.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnS.setForeground(new java.awt.Color(255, 255, 255));
        btnS.setText("S");
        btnS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS.setPreferredSize(new java.awt.Dimension(100, 50));
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnD.setBackground(new java.awt.Color(129, 131, 132));
        btnD.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnD.setForeground(new java.awt.Color(255, 255, 255));
        btnD.setText("D");
        btnD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnD.setPreferredSize(new java.awt.Dimension(100, 50));
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnV.setBackground(new java.awt.Color(129, 131, 132));
        btnV.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnV.setForeground(new java.awt.Color(255, 255, 255));
        btnV.setText("V");
        btnV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnV.setPreferredSize(new java.awt.Dimension(100, 50));
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        btnEnter.setBackground(new java.awt.Color(129, 131, 132));
        btnEnter.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Enter");
        btnEnter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnB.setBackground(new java.awt.Color(129, 131, 132));
        btnB.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnB.setForeground(new java.awt.Color(255, 255, 255));
        btnB.setText("B");
        btnB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnB.setPreferredSize(new java.awt.Dimension(100, 50));
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        txtJogada.setEditable(false);
        txtJogada.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        txtJogada.setForeground(new java.awt.Color(0, 0, 0));
        txtJogada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJogada.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtLetrasUsadas.setEditable(false);
        txtLetrasUsadas.setBackground(new java.awt.Color(18, 18, 19));
        txtLetrasUsadas.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        txtLetrasUsadas.setForeground(new java.awt.Color(255, 255, 255));
        txtLetrasUsadas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLetrasUsadas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.gray));
        txtLetrasUsadas.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtLetrasUsadas.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtLetrasUsadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetrasUsadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblForca, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtLetrasUsadas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPalavraChave, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCedilha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblForca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLetrasUsadas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(txtJogada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCedilha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarLetrasDigitadas(String letra){
        boolean letraJaFoiDigitada = false;
        for(int i = 0; i < letrasDigitadas.size(); i++){
            if(letrasDigitadas.get(i).equalsIgnoreCase(letra)){
                letraJaFoiDigitada = true;
            }
        }
        
        if(letraJaFoiDigitada == false){
            letrasDigitadas.add(letra);
        }
    }
    
    private String retornaLetrasDigitadas(){
        StringBuilder aux = new StringBuilder();
        String conjuntoLetras;
        
        for(int i = 0; i < letrasDigitadas.size(); i++){
            aux.append(letrasDigitadas.get(i));
            aux.append("  ");
        }
        
        conjuntoLetras = String.valueOf(aux);
        
        return conjuntoLetras;
    }
    
    
    private void atualizarForca(){
        iconForca = new ImageIcon(getClass().getResource(novoJogo.retornaEnderecoImg()));
    }
    
    private void estadoDoJogo() {
        
        String[] options = {"Novo jogo", "Sair"};
        String mensagemPerdeuJogo = "Que pena você não acertou a palavra \n" + "RESPOSTA: " + novoJogo.getPalavraChave().toUpperCase();
        String mensagemGanhouJogo = "Parabéns você acertou a palavra";
        
        if(novoJogo.gameOver()){
            if(novoJogo.completouBoneco()){
                int option = JOptionPane.showOptionDialog(null, mensagemPerdeuJogo, "Game Over", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, "Novo Jogo");
                
                if(option == 0){
                   new Main().setVisible(true); 
                   dispose();
                } else {
                    System.exit(0);
                }
                
            } else if (novoJogo.acertouPalavra()) {
                int option2 = JOptionPane.showOptionDialog(null, mensagemGanhouJogo, "Game Over", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, "Novo Jogo");
                
                if(option2 == 0){
                   new Main().setVisible(true); 
                   dispose();
                  
                } else {
                    System.exit(0);
                }
            }
            
        }
    }
    
    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        txtJogada.setText("Q");
    }//GEN-LAST:event_btnQActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        txtJogada.setText("N");

    }//GEN-LAST:event_btnNActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        txtJogada.setText("W");
    }//GEN-LAST:event_btnWActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        txtJogada.setText("M");

    }//GEN-LAST:event_btnMActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        txtJogada.setText("E");
    }//GEN-LAST:event_btnEActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        txtJogada.setText(null);
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        txtJogada.setText("R");
    }//GEN-LAST:event_btnRActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        txtJogada.setText("Z");

    }//GEN-LAST:event_btnZActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        txtJogada.setText("T");
    }//GEN-LAST:event_btnTActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        txtJogada.setText("Y");
    }//GEN-LAST:event_btnYActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        txtJogada.setText("X");

    }//GEN-LAST:event_btnXActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        txtJogada.setText("C");

    }//GEN-LAST:event_btnCActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        txtJogada.setText("U");
    }//GEN-LAST:event_btnUActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        txtJogada.setText("I");
    }//GEN-LAST:event_btnIActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        txtJogada.setText("O");
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        txtJogada.setText("P");
    }//GEN-LAST:event_btnPActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        txtJogada.setText("F");

    }//GEN-LAST:event_btnFActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        txtJogada.setText("G");

    }//GEN-LAST:event_btnGActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        txtJogada.setText("H");

    }//GEN-LAST:event_btnHActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        txtJogada.setText("J");

    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        txtJogada.setText("K");

    }//GEN-LAST:event_btnKActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        txtJogada.setText("L");

    }//GEN-LAST:event_btnLActionPerformed

    private void btnCedilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCedilhaActionPerformed
        txtJogada.setText("Ç");

    }//GEN-LAST:event_btnCedilhaActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        txtJogada.setText("A");
    }//GEN-LAST:event_btnAActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        txtJogada.setText("S");
    }//GEN-LAST:event_btnSActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        txtJogada.setText("D");
    }//GEN-LAST:event_btnDActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        txtJogada.setText("V");

    }//GEN-LAST:event_btnVActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        String letraDigitada = txtJogada.getText();
        novoJogo.checaPalavra(letraDigitada);
        lblPalavraChave.setText( novoJogo.atualizarJogo());
        
        guardarLetrasDigitadas(letraDigitada);
        txtLetrasUsadas.setText(retornaLetrasDigitadas());
        
        atualizarForca();
        lblForca.setIcon(iconForca);
        
        estadoDoJogo();
        
        txtJogada.setText(null);
        
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        txtJogada.setText("B");

    }//GEN-LAST:event_btnBActionPerformed

    private void txtLetrasUsadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetrasUsadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetrasUsadasActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCedilha;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JLabel lblForca;
    private javax.swing.JLabel lblPalavraChave;
    private javax.swing.JTextField txtJogada;
    private javax.swing.JTextField txtLetrasUsadas;
    // End of variables declaration//GEN-END:variables
}
